version: "3.8"
services:
  mysql:
    container_name: mysql_container
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=ecom_app
      - MYSQL_USER=ecom
      - MYSQL_PASSWORD=admin
    ports:
      - 3307:3306
    volumes:
      - ../docker-volumes/mysql:/var/lib/mysql
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mysql
    restart: always

      
      